import type { FC } from 'react';

/**
 * Simulation of magnetic fields generated by current loops.
 * TODO: Visualize field lines and allow parameter tweaking.
 */
const CurrentLoopSimulator: FC = () => (
  <div className="rounded-lg border border-dashed border-cyan-400/30 bg-cyan-500/5 p-4 text-sm text-cyan-50">
    Current Loop Simulator placeholder
  </div>
);

export default CurrentLoopSimulator;
